<a href="https://colab.research.google.com/github/Crash-overloaded/ML/blob/master/Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPUTER
# LABEL ENCODING
# ONE HOT ENCODING


In [1]:
import pandas as pd
df=pd.read_csv("http://13.234.66.67/summer19/datasets/info.csv")
#pos_sal=pd.read_csv("http://13.234.66.67/summer19/datasets/pos_sal.csv")
# Removing Header from csv file
features=df.iloc[:,0:4].values
print(features)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' nan 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


In [0]:
# Removing missing values or replacing missing value with some relevant data
  #info.describe()
  from sklearn.preprocessing import Imputer

In [262]:
# Strategy is the way of choosing missing value
# axis -> 0 = columns operations
# axis -> 1 = row operations
imp=Imputer(missing_values='NaN',axis=0,strategy='most_frequent')


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
# Selecting and tranforming 2 and 3rd column
# fitting extracts schema
# This is only fitting of columns that we want to process
impute=imp.fit(features[:,[1,2]]) # it tells where we have to apply imp function


In [264]:
# It extracts data
# Just aaplying 
features[:,[1,2]]=impute.transform(features[:,[1,2]])
features


array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 48000.0, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 27.0, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

# Replacing Country names and answer(Yes/no) with integer labels

In [0]:
# Replacing string with integers labels
from sklearn.preprocessing import LabelEncoder

In [0]:
enc=LabelEncoder() # Labelling country with integers

In [0]:
features[:,0]=enc.fit_transform(features[:,0])
features[:,-1]=enc.fit_transform(features[:,-1])

In [268]:
# France -> 0
# Germany -> 1
# Spain -> 2

# Also 0 for no and 1 for yes

features

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 48000.0, 1],
       [0, 35.0, 58000.0, 1],
       [2, 27.0, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [0]:
#Now encoding first column making subcolumn of first column
from sklearn.preprocessing import OneHotEncoder

In [0]:
# Categorical features is the column number whose we want to make subcolumns
firstcl=OneHotEncoder(categorical_features=[0]) # Editifying and defining exact column no where we want to make subcolumns or category


In [271]:
# Transforming columns to subcolumns and converting it into array 
features=firstcl.fit_transform(features).toarray() # After tranformation convert it into numpy array


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [273]:
# To show the data in integer
print(features.astype(int))

[[    1     0     0    44 72000     0]
 [    0     0     1    27 48000     1]
 [    0     1     0    30 54000     0]
 [    0     0     1    38 61000     0]
 [    0     1     0    40 48000     1]
 [    1     0     0    35 58000     1]
 [    0     0     1    27 52000     0]
 [    1     0     0    48 79000     1]
 [    0     1     0    50 83000     0]
 [    1     0     0    37 67000     1]]
